### ISSUE TITLE
技術的に決めておいたほうがいいことを決める

### ISSUE THREAD

**Issue by Takashi-kun** [mokmoku/poem#10]
* 今後開発始まって起こりそうな問題とか, 予め決めて置いたほうがいいことを列挙

#### 基本情報

- [ ] サーバ置く場所
    * AWS? GCP?
- [ ] 鍵/パスワードの管理
    * ユーザー(SSH, その他ツール)
    * AWS? とか
- [ ] 設定ファイルとかの管理方法
    * dev/production での差分をどうやって管理しようかな
    * 多分 Provisioning で Chef(Docker) 使うことになりそうだけど, そのリポジトリをグローバルで作っていいのか
- [x] ドキュメントの置き場所
    * Google Docs ? Redmine ?

#### セキュリティ的なこと

- [ ] VPN あったほうがいいのだろうか
- [ ] SSL証明書
    * アプリ(iOS, Android) なら HTTPS 必須じゃなかったっけ
- [ ] アカウント管理
    * 支払い含む

#### 開発関連

- [ ] 開発体制
    * まあこれはそもそもどういうのを作るか固まってからかな
- [ ] ソース(レシピ的なもの含む)管理場所
    * GitHub のパブリックはなー
    * GitLab 建てるのもなー
- [ ] 言語/フレームワーク
    * API, バッチもすべて1つの言語で統一しておきたいところ
    * (作る内容に依存するものでもないので)予め決めても良さそう
    * ↑それによって開発環境どう作るかとか構成とか考えられる

**その他に何かあったら追記よろ**

**Comment by t-kashima** [comment]
https://github.com/mokmoku/loveit-general/issues に移行したのでCloseにします:bow:
