### ISSUE TITLE
こういうサービスがええと思うんや。

### ISSUE THREAD

**Issue by keikidesu** [mokmoku/poem#3]
いきなり結論ベースで申し訳ないが、俺が今一番良いと思ってるサービスはこれ。

# 作りたいサービス
[wishbone](https://itunes.apple.com/us/app/wishbone-compare-anything/id836071680?mt=8)
基本路線はwishboneを思いっきり模倣してやろうと思っている

# wishboneとは？
* アメリカのティーンエイジャーの中で流行ってるソーシャルネットワーキングアプリ
* 毎朝、ポップカルチャーに関する 12 の質問「今日の 1 ダース」を受け取り、2 つの選択肢から答えを選ぶ
* そのデータをもとに統計的にどっちの方が多いか、身内ではどういう結果だったかを共有するアプリ
* アメリカだと3ヶ月で300万DLという爆発的な普及をしている
![13940201_1057028681058974_531496991_o](https://cloud.githubusercontent.com/assets/14269832/17501650/918b16f2-5e1b-11e6-9379-db902b1f90d2.jpg)

# 山本が思っている今のアプリ市場の現状
* 正直、今のご時世はアプリを当てづらい時期だといえると思う
* スマホシフトが起こってから5年以上が経ち、大体の領域がスマホ最適化され、UIも模倣が続いている
* こういう状況下で勝負出来るのは大きく分けて2つ
* 1つ目は大企業の圧倒的な力による泥臭い時間をかけた戦い（持続的イノベーション）
* 2つ目は爆発的に拡散する機能による短期型の戦い（破壊的イノベーション）

# 破壊的イノベーションが起こりやすい領域とは？
* デバイスチェンジが最適化されていない領域
* 爆発的な普及（拡散）がしやすい領域（主にはSNSやニッチ領域）

# wishboneは何の市場を破壊しているのか？
* 大きなくくりでいうと「余暇時間」
* 特に若者の「暇つぶし」の時間を潰している
* 主にはtwitterやfacebookなどの余暇時間だと思われる
* アメリカだとそれに加えsnapchatといったところか（ここらへんは要リサーチ）

# wishboneが良いと思った理由
* 副業としてスタートしてもスピード感を出せるかもしれないと思ったから

## スピード感が出ると思った理由
* コンテンツがシンプル
* ティーンエイジャー向けで拡散力がある
* ネタになりそうだし習慣化しやすそう
* コンテンツをユーザー自身が作ってくれる

# 参考記事
* http://blog.btrax.com/jp/2016/02/09/app-usa-millenials/
* http://mag.sendenkaigi.com/senden/201605/us-admarketing/007963.php

# その他まとめたいこと
* ビジネスモデル
* 日本の文化との相違点
* 普及プロセス
* サービスの継続性（飽きられて終わらないか）

# メッセージ
* wishboneよりもっとシンプルにする予定

**Comment by t-kashima** [comment]
> 毎朝、ポップカルチャーに関する 12 の質問「今日の 1 ダース」を受け取り、2 つの選択肢から答えを選ぶ

ちょどいい感じだね！おもしろそう。
うん！結論を出してくれるのすごく助かるし、そういう感じで進めたい！

**Comment by Takashi-kun** [comment]
# Wishbone 的なものについて

## Daily Dozen

* 朝○時と19時に12個のpop culture情報が流れてくる

## Community

*100個の質問が流れている
    * フォローなどは関係なく、トレンド的なものが流れてきている（と思う）

## 2択クイズ作成

* 2種類
    * 2枚の写真ベース
    * 1枚の写真ベース

* 写真選択
    * Take Photo
    * Choose From Library
    * Search Web = Webから取得
    * Stickers(ステッカー?)

* Friends
    * フォローしている人の投稿内容だけ表示される

* Profile

##  DM(Direct Message)

* 個人間
* グループ
* 2択クイズを作成可能
* 作成した2択クイズをベースにさらに2択クイズを作成可能
